login: &login
access_key_id: 1QHTGHD6D2FH3K1XC382
secret_access_key: HE9iMl9Mv5iaEgiWDvn6ZX6Vdvn8jNmRLyqdNN03
server: survival-project.s3.amazonaws.com
host: proxy.abdn.ac.uk
port: 8080

development:
bucket_name: survival-project
<<: *login

test:
bucket_name: survival-project
<<: *login


production:
bucket_name: surivial-project
<<: *login